---
# This workflow runs DangerJS to lint pull requests when they are opened, edited, reopened, or synchronized.
# It checks out the PR head and uses the shared DangerJS action to enforce contribution guidelines.
# Note: This will not work in the pull request where the workflow is added due to the `pull_request_target` trigger.

name: 🎓 DangerJS Pull Request linter

on:
  pull_request_target: {types: [opened, edited, reopened, synchronize]}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dangerjs:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out PR head
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run DangerJS over Pull request
        uses: espressif/shared-github-dangerjs@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # with:
          #   instructions-contributions-file: '.github/CONTRIBUTING.md'
