---
# NOTE: THIS WORKFLOW IS INTENDED TO BE USED ONLY IN THE .GITHUB ORG REPOSITORY.
#  THERE IS NO POINT TO COPY IT TO INDIVIDUAL PROJECTS.
#
# This workflow automatically syncs GitHub Actions workflows and configuration files from
#  the .github organization repository to other repositories within the organization.
# It uses the 'repo-file-sync-action' to propagate changes, ensuring consistency across all
#  targeted repositories.
# This workflow can be manually triggered (workflow_dispatch) to initiate the sync process.
#
# This workflow is triggered either manually or automatically when specific paths in this repo
#   are modified in the main branch.

name: Sync GitHub workflows to org repositories

on:
  workflow_dispatch:
  push: {branches: [main], paths: ['shared/**', '.github/workflows/**']}

jobs:
  sync-org-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          # SKIP_PR: true # Skips the creation of a PR if set to true.
          ASSIGNEES: ${{ github.actor }} # Automatically assigns the user who triggers the workflow.
          BRANCH_PREFIX: automation # Branch prefix used for the sync PRs.
          COMMIT_PREFIX: 'ci(sync-org-files): ' # Prefix for commit messages.
          CONFIG_PATH: .github/org-sync-files # Path to the sync configuration file.
          GH_PAT: ${{ secrets.GH_PAT }} # Use an organizational bot token with appropriate permissions.
          ORIGINAL_MESSAGE: true
          OVERWRITE_EXISTING_PR: true # Allows overwriting of existing PRs to avoid duplication.
          # PR_BODY: 'This PR was automatically generated by the Sync GitHub workflows to org repositories workflow.'
          # PR_LABELS: AutoUpdate # PR labels help categorize and track these updates.
          TEAM_REVIEWERS: ci # Team assigned to review the sync PRs.
          # TODO: Update TEAM_REVIEWERS to Espressif/ci when integrating into the main organization.

          GIT_EMAIL: tomas.sebestik@espressif.com
          GIT_USERNAME: tomassebestik
          # GIT_EMAIL: bot@espressif.com
          # GIT_USERNAME: espressif-bot
